NUMPY AND PANDAS

In [ ]:
import numpy as np
import pandas as pd

que 1


In [ ]:
arr1 = np.arange(1, 11)
matrix = arr1.reshape(2, 5)

print("Que 1")
print(matrix)

Que 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


que 2

In [ ]:
arr2 = np.arange(1, 21)

print("\nQue 2")
print("Original Array:")
print(arr2)

print("Elements from index 5 to 15:")
print(arr2[5:16])


Que 2
Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Elements from index 5 to 15:
[ 6  7  8  9 10 11 12 13 14 15 16]


que 3

In [ ]:
print("\nQue 3")
print("Mean =", np.mean(arr2))
print("Median =", np.median(arr2))
print("Standard Deviation =", np.std(arr2))


Que 3
Mean = 10.5
Median = 10.5
Standard Deviation = 5.766281297335398


que4


In [ ]:
x = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])

y = np.array([1, 2, 3, 4])

result = x - y

print("\nQue 4")
print("Array x:")
print(x)

print("Array y:")
print(y)

print("Result after subtraction:")
print(result)


Que 4
Array x:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Array y:
[1 2 3 4]
Result after subtraction:
[[  9  18  27  36]
 [ 49  58  67  76]
 [ 89  98 107 116]]


que 5

In [ ]:
data = {
    "Name": ["Arun", "Anu", "Rahul", "Sneha", "Vishnu","Meera", "Akhil", "Diya", "Nikhil", "Riya"],
    "Age": [22, 28, 35, 31, 24, 29, 40, 33, 27, 30],
    "Gender": ["Male", "Female", "Male", "Female", "Male","Female", "Male", "Female", "Male", "Female"]
}

df = pd.DataFrame(data)

print("\nQuestion 5")
print(df)


Question 5
     Name  Age  Gender
0    Arun   22    Male
1     Anu   28  Female
2   Rahul   35    Male
3   Sneha   31  Female
4  Vishnu   24    Male
5   Meera   29  Female
6   Akhil   40    Male
7    Diya   33  Female
8  Nikhil   27    Male
9    Riya   30  Female


5.1


In [ ]:
occupations = [
    "Programmer", "Manager", "Analyst","Programmer", "Manager", "Analyst", "Programmer", "Manager", "Analyst", "Programmer"
]

df["Occupation"] = occupations

print("\nDataFrame after adding Occupation:")
print(df)


DataFrame after adding Occupation:
     Name  Age  Gender  Occupation
0    Arun   22    Male  Programmer
1     Anu   28  Female     Manager
2   Rahul   35    Male     Analyst
3   Sneha   31  Female  Programmer
4  Vishnu   24    Male     Manager
5   Meera   29  Female     Analyst
6   Akhil   40    Male  Programmer
7    Diya   33  Female     Manager
8  Nikhil   27    Male     Analyst
9    Riya   30  Female  Programmer


5.2

In [ ]:
print("\nRows where Age >= 30")
print(df[df["Age"] >= 30])


Rows where Age >= 30
    Name  Age  Gender  Occupation
2  Rahul   35    Male     Analyst
3  Sneha   31  Female  Programmer
6  Akhil   40    Male  Programmer
7   Diya   33  Female     Manager
9   Riya   30  Female  Programmer


5.3

In [ ]:
df.to_csv("students.csv", index=False)

new_df = pd.read_csv("students.csv")

print("\nData read from CSV:")
print(new_df)


Data read from CSV:
     Name  Age  Gender  Occupation
0    Arun   22    Male  Programmer
1     Anu   28  Female     Manager
2   Rahul   35    Male     Analyst
3   Sneha   31  Female  Programmer
4  Vishnu   24    Male     Manager
5   Meera   29  Female     Analyst
6   Akhil   40    Male  Programmer
7    Diya   33  Female     Manager
8  Nikhil   27    Male     Analyst
9    Riya   30  Female  Programmer
